/**
 * Contenido de la vista de águila de SIR Plus (Sistema Integral de Recaudación
 * remasterizado) — cuatro capas: Infraestructura, DevOps, DevSecOps y Sistema.
 *
 * IMPORTANTE sobre la naturaleza de estos datos:
 *   · Todo nace en estado "sin verificar". El panel NO afirma que algo exista o
 *     funcione: plantea qué hay que comprobar y con qué evidencia se comprueba.
 *   · `fuente` distingue de dónde sale cada punto:
 *       "zoho"    → tarea real registrada en Zoho (JAL-SIR+ o "aplica a todos
 *                   los proyectos"), o hecho tomado del tablero de operación.
 *       "codigo"  → comportamiento documentado en la Guía Funcional OPENSIR,
 *                   elaborada a partir del código fuente (rama dev-vps).
 *       "reco"    → recomendación de práctica, todavía no confirmada con el
 *                   equipo. Se debe validar antes de darla por cierta.
 */

export type Fuente = "zoho" | "codigo" | "reco";

export interface Check {
  id: string;
  /** Qué hay que reforzar o verificar. */
  label: string;
  /** Con qué se verifica y qué evidencia queda documentada. */
  verifica: string;
  fuente: Fuente;
}

export interface Nodo {
  id: string;
  nombre: string;
  resumen: string;
  /** La pregunta que este nodo debe poder responder de un vistazo. */
  pregunta?: string;
  checks: Check[];
}

export interface Grupo {
  id: string;
  nombre: string;
  nodos: Nodo[];
}

export interface Capa {
  id: string;
  nombre: string;
  sub: string;
  descripcion: string;
  color: string;
  grupos: Grupo[];
}

// ══════════════════════════════════════════════════════════════════════════════
// CAPA 1 — INFRAESTRUCTURA
// ══════════════════════════════════════════════════════════════════════════════

const INFRAESTRUCTURA: Capa = {
  id: "infra",
  nombre: "Infraestructura",
  sub: "Dónde vive y cuánto aguanta",
  descripcion:
    "El piso sobre el que corre SIR Plus: cómputo, datos, red y continuidad. Si esta capa falla, no importa qué tan bien esté el código: la recaudación se detiene.",
  color: "#0EA5E9",
  grupos: [
    {
      id: "infra-computo",
      nombre: "Cómputo y disponibilidad",
      nodos: [
        {
          id: "infra.servidores",
          nombre: "Servidores y ubicación",
          resumen: "Dónde está desplegado cada componente de Jalisco y con qué recursos.",
          pregunta: "¿Sabemos exactamente en qué máquina vive cada pieza del SIR de Jalisco?",
          checks: [
            { id: "infra.servidores.inventario", fuente: "reco",
              label: "Inventario de servidores de Jalisco: front, backend, BD, reporteador, RETYS, portal, BI",
              verifica: "Documento de arquitectura con IP/hostname, recursos (CPU, RAM, disco), sistema operativo, responsable y ambiente de cada máquina" },
            { id: "infra.servidores.instalacion", fuente: "zoho",
              label: "Instalación del ambiente completo de Jalisco con librerías actualizadas",
              verifica: "Tarea de operación 'JALISCO — Instalación de ambiente completo': acta de instalación con versiones de Python/Django, Node y dependencias" },
            { id: "infra.servidores.sizing", fuente: "reco",
              label: "Dimensionamiento contra la carga real de Jalisco (padrón, refrendo vehicular, cierres de mes)",
              verifica: "Cálculo de usuarios concurrentes esperados por ventanilla y portal vs. recursos asignados, firmado con el cliente" },
            { id: "infra.servidores.aislamiento", fuente: "zoho",
              label: "Un solo sistema por servidor: evitar el VPS sobrepoblado",
              verifica: "Plan de distribución de sistemas — que Jalisco no comparta VPS con otras entidades ni con ambientes de prueba" },
            { id: "infra.servidores.hardening", fuente: "reco",
              label: "Endurecimiento del sistema operativo (usuarios, puertos, SSH, actualizaciones)",
              verifica: "Checklist de hardening aplicado y evidencia de la última actualización de paquetes de seguridad" },
          ],
        },
        {
          id: "infra.ha",
          nombre: "Alta disponibilidad y réplicas",
          resumen: "Qué pasa cuando una máquina se cae en horario de recaudación.",
          pregunta: "¿Tenemos réplicas? ¿Qué pasa cuando se caiga la operación del SIR?",
          checks: [
            { id: "infra.ha.replica_bd", fuente: "reco",
              label: "Réplica de la base de datos (al menos una standby en streaming replication)",
              verifica: "Consulta de estado de replicación mostrando retraso en segundos, y evidencia del último simulacro de promoción de la réplica" },
            { id: "infra.ha.app_redundante", fuente: "reco",
              label: "Más de una instancia de aplicación (backend y portal) detrás de un balanceador",
              verifica: "Prueba documentada: apagar una instancia en horario controlado y comprobar que el servicio sigue respondiendo" },
            { id: "infra.ha.punto_unico", fuente: "reco",
              label: "Mapa de puntos únicos de falla: BD, storage, pasarela de pago, timbrado, DNS",
              verifica: "Tabla de componentes con la columna '¿qué se cae si esto se cae?' y el plan de mitigación de cada uno" },
            { id: "infra.ha.degradado", fuente: "reco",
              label: "Modo degradado definido: qué se puede seguir cobrando si cae el pago en línea o el timbrado",
              verifica: "Procedimiento operativo para ventanilla cuando falla un servicio externo, acordado con el área de recaudación del cliente" },
            { id: "infra.ha.objetivo", fuente: "reco",
              label: "Compromiso de disponibilidad acordado con el cliente (ventana de mantenimiento incluida)",
              verifica: "Acuerdo de nivel de servicio firmado y tablero de disponibilidad medido mes a mes" },
          ],
        },
        {
          id: "infra.balanceo",
          nombre: "Balanceo de carga",
          resumen: "Reparto de tráfico entre instancias y punto único de entrada.",
          pregunta: "¿Tenemos balanceadores?",
          checks: [
            { id: "infra.balanceo.existe", fuente: "reco",
              label: "Balanceador de capa 7 al frente del backend y del portal ciudadano",
              verifica: "Configuración del balanceador versionada en repositorio y diagrama de flujo de tráfico" },
            { id: "infra.balanceo.health", fuente: "reco",
              label: "Health checks reales (que consulten BD y dependencias, no solo que el puerto responda)",
              verifica: "Endpoint de salud documentado y prueba de que el balanceador saca de rotación una instancia enferma" },
            { id: "infra.balanceo.sesion", fuente: "reco",
              label: "Manejo de sesión compatible con varias instancias (sesión externa, no en memoria del proceso)",
              verifica: "Prueba de que un usuario autenticado no pierde sesión al cambiar de instancia" },
            { id: "infra.balanceo.tls", fuente: "reco",
              label: "Terminación TLS y renovación automática de certificados",
              verifica: "Fecha de expiración de cada certificado y evidencia de la renovación automática funcionando" },
          ],
        },
        {
          id: "infra.gateway",
          nombre: "API Gateway",
          resumen: "Puerta única para las APIs: autenticación, límites y trazabilidad.",
          pregunta: "¿Tenemos contemplados API gateways?",
          checks: [
            { id: "infra.gateway.existe", fuente: "reco",
              label: "Gateway único para las APIs del SIR, del portal y de RETYS",
              verifica: "Diagrama de entrada de tráfico donde ningún servicio quede expuesto directo a internet" },
            { id: "infra.gateway.rate", fuente: "reco",
              label: "Límite de peticiones por IP y por usuario (protege consulta de adeudos y login del portal)",
              verifica: "Configuración de rate limit y prueba de que se activa al superar el umbral" },
            { id: "infra.gateway.versionado", fuente: "reco",
              label: "Versionado de API y política de deprecación para no romper canales",
              verifica: "Convención de rutas versionadas y matriz de qué versión consume cada canal (admin, portal, RETYS, app)" },
            { id: "infra.gateway.trazabilidad", fuente: "zoho",
              label: "Cada endpoint mapeado con su acción de negocio, para poder auditar",
              verifica: "Tarea 'Análisis de endpoints que se consumen en procesos prioritarios para auditar' — catálogo endpoint → acción auditable" },
            { id: "infra.gateway.contratos", fuente: "reco",
              label: "Documentación viva de la API (OpenAPI) publicada para el equipo y el cliente",
              verifica: "Especificación generada desde el código y accesible en cada ambiente" },
          ],
        },
      ],
    },
    {
      id: "infra-datos",
      nombre: "Datos y continuidad",
      nodos: [
        {
          id: "infra.respaldos",
          nombre: "Respaldos",
          resumen: "Copias de seguridad y, sobre todo, pruebas de que se pueden restaurar.",
          pregunta: "Si perdemos la base hoy, ¿cuánto perdemos y cuánto tardamos en volver?",
          checks: [
            { id: "infra.respaldos.frecuencia", fuente: "reco",
              label: "Respaldo automático de base de datos con frecuencia definida y retención documentada",
              verifica: "Bitácora de respaldos de los últimos 30 días con tamaño y resultado de cada ejecución" },
            { id: "infra.respaldos.offsite", fuente: "reco",
              label: "Copia fuera del servidor de producción (otra ubicación o proveedor)",
              verifica: "Evidencia de que el respaldo existe en un destino independiente del servidor que respalda" },
            { id: "infra.respaldos.restauracion", fuente: "reco",
              label: "Prueba real de restauración — un respaldo sin restaurar no es un respaldo",
              verifica: "Acta del último ejercicio de restauración en ambiente aislado, con tiempo total medido" },
            { id: "infra.respaldos.pitr", fuente: "reco",
              label: "Recuperación a un punto en el tiempo, para revertir un error de captura o un proceso masivo mal aplicado",
              verifica: "Configuración de archivado de WAL y prueba de restauración a una hora específica" },
            { id: "infra.respaldos.archivos", fuente: "zoho",
              label: "Respaldo de archivos y documentos del bucket, no solo de la base",
              verifica: "Estrategia de buckets por entidad y ambiente, con versionado y política de retención" },
          ],
        },
        {
          id: "infra.drp",
          nombre: "Recuperación ante desastres (DRP)",
          resumen: "El plan escrito de qué hacer cuando todo se cae, y quién lo ejecuta.",
          pregunta: "¿Tenemos políticas de recuperación de desastres?",
          checks: [
            { id: "infra.drp.documento", fuente: "reco",
              label: "Plan de recuperación escrito, con responsables nombrados y teléfonos",
              verifica: "Documento DRP firmado, con fecha de última revisión menor a un año" },
            { id: "infra.drp.rpo_rto", fuente: "reco",
              label: "Objetivos declarados: cuánta información aceptamos perder (RPO) y en cuánto tiempo volvemos (RTO)",
              verifica: "RPO y RTO por componente, acordados con el cliente y contrastados contra la última prueba real" },
            { id: "infra.drp.simulacro", fuente: "reco",
              label: "Simulacro periódico — al menos uno al año, con hallazgos y correcciones",
              verifica: "Reporte del último simulacro: qué falló, qué se corrigió y quién dio seguimiento" },
            { id: "infra.drp.comunicacion", fuente: "reco",
              label: "Protocolo de comunicación durante una caída: quién avisa al cliente y por qué medio",
              verifica: "Árbol de escalamiento y plantillas de aviso, validados con la dirección" },
            { id: "infra.drp.contable", fuente: "zoho",
              label: "Procedimiento de cuadre contable posterior a un incidente",
              verifica: "Aprendizaje de los descuadres de Nayarit: guion de conciliación de recibos, abonos y depósitos tras la recuperación" },
          ],
        },
        {
          id: "infra.bd",
          nombre: "Base de datos y desempeño",
          resumen: "Salud, índices y comportamiento de la BD bajo carga real.",
          pregunta: "¿La base aguanta un cierre de mes y un refrendo masivo?",
          checks: [
            { id: "infra.bd.indices", fuente: "zoho",
              label: "Índices en los campos de búsqueda intensiva de padrones y cartera",
              verifica: "Antecedente en Nayarit: indexación de placa y configuración. Plan de ejecución con tiempos antes/después" },
            { id: "infra.bd.consultas", fuente: "reco",
              label: "Monitoreo de consultas lentas y bloqueos en producción",
              verifica: "Reporte periódico de consultas más costosas y plan de optimización con responsable" },
            { id: "infra.bd.bitacora", fuente: "zoho",
              label: "Control del crecimiento de la bitácora: qué se registra y qué no",
              verifica: "Tarea 'Revisión de endpoint /recaudacion/descuentos — consume mucho espacio en bitácora'. Política de niveles de log y retención" },
            { id: "infra.bd.masivos", fuente: "zoho",
              label: "Procesos masivos de cartera fuera de línea, sin bloquear la operación",
              verifica: "Tarea JAL-SIR+ 'Actualización/Persistencia Masiva de Cartera' (UMA anual, INPC mensual): ventana de ejecución, tiempo medido y plan de reversa" },
            { id: "infra.bd.mantenimiento", fuente: "reco",
              label: "Mantenimiento programado: estadísticas, vacuum/autovacuum, crecimiento de disco",
              verifica: "Calendario de mantenimiento y gráfica de crecimiento de disco de los últimos meses" },
          ],
        },
        {
          id: "infra.migracion",
          nombre: "Migración de datos del cliente",
          resumen: "El origen histórico de Jalisco y su fidelidad al migrarse.",
          pregunta: "¿Los datos que llegan del sistema anterior cuadran con el nuevo?",
          checks: [
            { id: "infra.migracion.origen", fuente: "zoho",
              label: "Mapeo de tablas fuente del cliente (Informix) hacia el modelo de SIR Plus",
              verifica: "Varias tareas JAL-SIR+ nombran tablas Informix (notificacion, estacionometros, multanofisc, hipoteca, pdrcertdep). Diccionario de equivalencias campo a campo" },
            { id: "infra.migracion.cuadre", fuente: "reco",
              label: "Cuadre de totales entre origen y destino: registros, saldos y adeudos",
              verifica: "Script de conciliación con resultados por padrón, firmado por el cliente antes de salir a producción" },
            { id: "infra.migracion.reversa", fuente: "reco",
              label: "Plan de reversa de la migración y congelamiento del sistema origen",
              verifica: "Procedimiento de corte documentado: fecha, hora, responsable y punto de retorno" },
            { id: "infra.migracion.ensayo", fuente: "reco",
              label: "Al menos un ensayo completo de migración antes del corte real",
              verifica: "Bitácora del ensayo con duración total y lista de incidencias resueltas" },
          ],
        },
      ],
    },
    {
      id: "infra-red",
      nombre: "Red, entrega y perímetro",
      nodos: [
        {
          id: "infra.perimetro",
          nombre: "Perímetro y acceso",
          resumen: "Quién puede tocar la infraestructura y por dónde entra.",
          pregunta: "¿Estamos seguros en el borde?",
          checks: [
            { id: "infra.perimetro.waf", fuente: "zoho",
              label: "WAF delante del portal ciudadano y del admin",
              verifica: "Antecedente Oaxaca Estado: WAF + DNS configurados. Reglas activas y reporte de bloqueos del último mes" },
            { id: "infra.perimetro.vpn", fuente: "zoho",
              label: "Acceso administrativo solo por VPN — nada de administración expuesta a internet",
              verifica: "Tarea de operación 'Activar VPN en VPS'. Lista de usuarios con acceso y última revisión de altas/bajas" },
            { id: "infra.perimetro.firewall", fuente: "reco",
              label: "Firewall con puertos mínimos abiertos y segmentación entre aplicación y base de datos",
              verifica: "Reglas de firewall versionadas y escaneo de puertos externo que confirme que solo 80/443 responden" },
            { id: "infra.perimetro.dns", fuente: "zoho",
              label: "Nomenclatura de DNS uniforme por sistema, entidad y ambiente",
              verifica: "Esquema acordado sir / api-sir / retys / reporteador / portal / bi — entidad — ambiente, aplicado también en Jalisco" },
            { id: "infra.perimetro.bastion", fuente: "reco",
              label: "Acceso a servidores por bastión con llaves nominales, sin usuarios compartidos",
              verifica: "Bitácora de accesos SSH y evidencia de que no existen credenciales compartidas" },
          ],
        },
        {
          id: "infra.almacenamiento",
          nombre: "Almacenamiento de documentos",
          resumen: "Dónde viven los archivos que sube el ciudadano y los que emite el sistema.",
          pregunta: "¿Los documentos del ciudadano están protegidos y respaldados?",
          checks: [
            { id: "infra.almacenamiento.separacion", fuente: "zoho",
              label: "Buckets separados por entidad y por ambiente — que pruebas nunca escriba en producción",
              verifica: "Tarea de operación 'Planear manejo de archivos bucket'. Nombres de bucket y credenciales distintas por ambiente" },
            { id: "infra.almacenamiento.acceso", fuente: "reco",
              label: "Sin acceso público directo a los documentos: enlaces firmados y temporales",
              verifica: "Prueba de que una URL de documento expira y no es adivinable" },
            { id: "infra.almacenamiento.cifrado", fuente: "reco",
              label: "Cifrado en reposo de documentos con datos personales",
              verifica: "Configuración de cifrado del bucket y registro de dónde se guardan las llaves" },
            { id: "infra.almacenamiento.retencion", fuente: "reco",
              label: "Política de retención y borrado alineada con el aviso de privacidad",
              verifica: "Tabla de tipos de documento con su plazo de conservación, validada con el área jurídica del cliente" },
          ],
        },
        {
          id: "infra.integraciones",
          nombre: "Integraciones externas",
          resumen: "Servicios de terceros de los que depende el cobro.",
          pregunta: "¿Qué pasa con la recaudación si un tercero deja de responder?",
          checks: [
            { id: "infra.integraciones.inventario", fuente: "codigo",
              label: "Inventario de integraciones: pasarela de pago, terminal electrónica, banca, timbrado CFDI, padrón vehicular",
              verifica: "Ficha por integración: proveedor, contacto, ambiente de pruebas, credenciales y responsable interno" },
            { id: "infra.integraciones.timbrado", fuente: "zoho",
              label: "Timbrado CFDI con URLs y proveedor confirmados por ambiente",
              verifica: "Antecedente AUTOPAC: URLs de timbrado listas y pase a producción evaluado con DevOps" },
            { id: "infra.integraciones.conciliacion", fuente: "zoho",
              label: "Conciliación automática de lo cobrado contra lo que reporta el banco y la pasarela",
              verifica: "Historial de descuadres en Nayarit (pagos externos, recibos duplicados, línea de captura). Reporte diario de conciliación con diferencias en cero" },
            { id: "infra.integraciones.reintentos", fuente: "reco",
              label: "Reintentos, tiempos de espera e idempotencia en cada llamada externa",
              verifica: "Prueba de que un pago no se duplica si el tercero responde tarde o dos veces" },
            { id: "infra.integraciones.monitoreo", fuente: "reco",
              label: "Alerta cuando un tercero se degrada, antes de que lo reporte la ventanilla",
              verifica: "Monitor sintético por integración con umbral de latencia y error" },
          ],
        },
        {
          id: "infra.observabilidad",
          nombre: "Monitoreo y observabilidad",
          resumen: "Enterarnos de los problemas antes que el cliente.",
          pregunta: "¿Cómo sabemos que el SIR está sano en este momento?",
          checks: [
            { id: "infra.observabilidad.infra", fuente: "zoho",
              label: "Monitoreo de servidores: CPU, memoria, disco, servicios caídos",
              verifica: "Antecedente 'Instalación de monitoreo de servidores' en Oaxaca Estado. Tablero activo también para Jalisco" },
            { id: "infra.observabilidad.uptime", fuente: "reco",
              label: "Monitor externo de disponibilidad del portal y del admin, con alerta a un canal atendido",
              verifica: "Historial de disponibilidad de los últimos 90 días y evidencia de que las alertas llegan a alguien de guardia" },
            { id: "infra.observabilidad.logs", fuente: "reco",
              label: "Logs centralizados y consultables de todos los componentes",
              verifica: "Prueba: reconstruir qué pasó en un cobro específico buscando por folio en el visor de logs" },
            { id: "infra.observabilidad.negocio", fuente: "reco",
              label: "Alertas de negocio, no solo técnicas: caída de recibos por hora, pagos en línea en cero",
              verifica: "Definición de métricas de recaudación monitoreadas y umbrales de alerta acordados" },
            { id: "infra.observabilidad.guardia", fuente: "reco",
              label: "Rol de guardia definido para horario de operación de ventanillas",
              verifica: "Calendario de guardias publicado y tiempo de respuesta medido en los últimos incidentes" },
          ],
        },
      ],
    },
    {
      id: "infra-reco",
      nombre: "Lo que recomiendo añadir a esta capa",
      nodos: [
        {
          id: "infra.extra",
          nombre: "Piezas que suelen faltar",
          resumen: "Componentes que no siempre se contemplan y que evitan incendios después.",
          pregunta: "¿Qué más deberíamos poner en la capa de infraestructura?",
          checks: [
            { id: "infra.extra.cache", fuente: "reco",
              label: "Caché y cola de trabajos (por ejemplo Redis + trabajos en segundo plano)",
              verifica: "Procesos pesados — reportes masivos, actualización de cartera, envío de documentos — fuera del ciclo de la petición web" },
            { id: "infra.extra.iac", fuente: "reco",
              label: "Infraestructura como código: que un ambiente se pueda recrear sin memoria de nadie",
              verifica: "Repositorio con la definición del ambiente y evidencia de haber recreado uno desde cero" },
            { id: "infra.extra.secretos", fuente: "reco",
              label: "Gestor de secretos: credenciales fuera de archivos .env sueltos en el servidor",
              verifica: "Bóveda de secretos con acceso por rol y bitácora de consultas" },
            { id: "infra.extra.hora", fuente: "reco",
              label: "Sincronización horaria estricta en todos los servidores",
              verifica: "La hora de un recibo tiene efecto fiscal: evidencia de NTP activo y zona horaria idéntica en aplicación y base de datos" },
            { id: "infra.extra.carga", fuente: "reco",
              label: "Pruebas de carga antes de cada temporada alta (refrendo, cierre anual)",
              verifica: "Reporte de prueba de carga con usuarios concurrentes soportados y punto de quiebre identificado" },
            { id: "infra.extra.cdn", fuente: "reco",
              label: "CDN para el portal ciudadano",
              verifica: "Medición de tiempo de carga del portal desde distintos puntos del estado" },
            { id: "infra.extra.costos", fuente: "reco",
              label: "Control de costo de infraestructura por entidad",
              verifica: "Reporte mensual de gasto por proyecto, insumo para la negociación con el cliente" },
          ],
        },
      ],
    },
  ],
};

// ══════════════════════════════════════════════════════════════════════════════
// CAPA 2 — DEVOPS
// ══════════════════════════════════════════════════════════════════════════════

const DEVOPS: Capa = {
  id: "devops",
  nombre: "DevOps",
  sub: "Cómo llega el código a producción",
  descripcion:
    "El camino entre el repositorio y la ventanilla. Aquí se decide qué tan rápido se corrige un error y qué tan seguro es publicar un cambio en plena recaudación.",
  color: "#8B5CF6",
  grupos: [
    {
      id: "devops-codigo",
      nombre: "Código y ramas",
      nodos: [
        {
          id: "devops.repos",
          nombre: "Repositorios por proyecto",
          resumen: "Que Jalisco tenga su propia línea de código identificable.",
          pregunta: "¿Sabemos con certeza qué código está corriendo en Jalisco?",
          checks: [
            { id: "devops.repos.separacion", fuente: "zoho",
              label: "Repositorio exclusivo por proyecto, con ramas ordenadas",
              verifica: "Iniciativa en curso 'Repositorios por proyecto' (orden: iPROVINAY → Navojoa → Oaxaca → Tlajomulco). Definir dónde entra Jalisco / SIR Plus" },
            { id: "devops.repos.ramas", fuente: "reco",
              label: "Estrategia de ramas escrita: qué rama va a cada ambiente y quién aprueba la fusión",
              verifica: "Documento de una página y configuración de protección de la rama de producción" },
            { id: "devops.repos.pr", fuente: "reco",
              label: "Revisión obligatoria por otra persona antes de fusionar",
              verifica: "Configuración del repositorio exigiendo aprobación, y muestreo de los últimos cambios fusionados" },
            { id: "devops.repos.commits", fuente: "reco",
              label: "Cada cambio ligado a su tarea de Zoho",
              verifica: "Convención de mensaje con el folio de la tarea, para poder rastrear de un error a su origen" },
          ],
        },
        {
          id: "devops.versiones",
          nombre: "Versiones y liberaciones",
          resumen: "Saber qué versión tiene cada entidad y qué trae dentro.",
          pregunta: "¿Qué versión está en producción y qué cambió respecto a la anterior?",
          checks: [
            { id: "devops.versiones.tag", fuente: "reco",
              label: "Versión etiquetada y visible dentro del sistema (pie de página o pantalla de ayuda)",
              verifica: "Abrir el SIR de Jalisco y poder leer la versión exacta desplegada" },
            { id: "devops.versiones.matriz", fuente: "reco",
              label: "Matriz de qué versión corre en cada entidad y ambiente",
              verifica: "Tablero de liberaciones actualizado tras cada despliegue" },
            { id: "devops.versiones.notas", fuente: "reco",
              label: "Nota de liberación por versión, en lenguaje entendible por el cliente",
              verifica: "Documento por liberación con cambios, riesgos y pasos posteriores" },
            { id: "devops.versiones.replicar", fuente: "zoho",
              label: "Mecanismo para replicar una corrección a las demás entidades",
              verifica: "Antecedente 'Replicar optimizaciones de Tlajomulco en productivos'. Registro de qué corrección se aplicó a qué entidad y cuándo" },
          ],
        },
      ],
    },
    {
      id: "devops-entrega",
      nombre: "Integración y entrega",
      nodos: [
        {
          id: "devops.ci",
          nombre: "Integración continua",
          resumen: "Que la máquina revise el código antes que las personas.",
          pregunta: "¿Cada cambio se compila y se prueba solo?",
          checks: [
            { id: "devops.ci.pipeline", fuente: "reco",
              label: "Pipeline que compile e instale dependencias en cada cambio",
              verifica: "Historial de ejecuciones del pipeline con resultado por rama" },
            { id: "devops.ci.pruebas", fuente: "reco",
              label: "Pruebas automatizadas del cálculo fiscal: cargos, recargos, descuentos, actualizaciones",
              verifica: "El área donde más falla el SIR históricamente. Suite con casos reales y su porcentaje de cobertura" },
            { id: "devops.ci.lint", fuente: "reco",
              label: "Análisis estático y formato uniforme que bloquee la fusión si falla",
              verifica: "Configuración del pipeline y evidencia de un cambio rechazado por esta regla" },
            { id: "devops.ci.regresion", fuente: "reco",
              label: "Suite de regresión de los procesos críticos: cobro, orden de pago, convenio, CFDI",
              verifica: "Lista de casos de regresión ejecutados antes de cada liberación, con resultado documentado" },
          ],
        },
        {
          id: "devops.cd",
          nombre: "Despliegue continuo",
          resumen: "Publicar sin sobresaltos y poder volver atrás.",
          pregunta: "¿Tenemos despliegue continuo? ¿Cuál?",
          checks: [
            { id: "devops.cd.automatico", fuente: "reco",
              label: "Despliegue automatizado y repetible — no pasos manuales en el servidor",
              verifica: "Definición del pipeline de despliegue en el repositorio y evidencia de al menos un despliegue automático" },
            { id: "devops.cd.aprobacion", fuente: "reco",
              label: "Aprobación explícita para producción, con ventana acordada con el cliente",
              verifica: "Bitácora de aprobaciones con quién autorizó cada salida a producción" },
            { id: "devops.cd.rollback", fuente: "reco",
              label: "Reversa probada: volver a la versión anterior en minutos",
              verifica: "Ejercicio de reversa cronometrado en ambiente de pruebas" },
            { id: "devops.cd.migraciones", fuente: "reco",
              label: "Migraciones de base de datos versionadas, reversibles y ejecutadas por el pipeline",
              verifica: "Ninguna migración aplicada a mano en producción. Bitácora de migraciones por ambiente" },
            { id: "devops.cd.progresivo", fuente: "reco",
              label: "Despliegue progresivo o por interruptor de funcionalidad para cambios de riesgo",
              verifica: "Mecanismo para activar una funcionalidad nueva solo para ciertas unidades recaudadoras" },
          ],
        },
        {
          id: "devops.ambientes",
          nombre: "Ambientes",
          resumen: "Que probar sirva de algo: pruebas parecidas a producción.",
          pregunta: "¿Lo que probamos en QA se comporta igual en producción?",
          checks: [
            { id: "devops.ambientes.tres", fuente: "reco",
              label: "Ambientes separados de desarrollo, QA y producción para Jalisco",
              verifica: "URLs, credenciales y responsables por ambiente, con DNS conforme a la nomenclatura acordada" },
            { id: "devops.ambientes.paridad", fuente: "reco",
              label: "Misma versión de motor de base de datos, librerías y configuración entre QA y producción",
              verifica: "Comparativo de versiones documentado antes de cada liberación mayor" },
            { id: "devops.ambientes.datos", fuente: "reco",
              label: "Datos de prueba anonimizados — nunca datos personales reales en QA",
              verifica: "Procedimiento de enmascaramiento y evidencia de su ejecución en la última copia hacia QA" },
            { id: "devops.ambientes.config", fuente: "reco",
              label: "Configuración por variables de ambiente, no valores fijos en el código",
              verifica: "Revisión de que URLs y credenciales no están escritas dentro del código fuente" },
          ],
        },
      ],
    },
    {
      id: "devops-operacion",
      nombre: "Operación del cambio",
      nodos: [
        {
          id: "devops.runbooks",
          nombre: "Procedimientos y guardia",
          resumen: "Que cualquiera del equipo pueda atender un incidente, no solo quien lo construyó.",
          pregunta: "Si el responsable no está, ¿alguien más puede levantar el sistema?",
          checks: [
            { id: "devops.runbooks.operativos", fuente: "reco",
              label: "Guías de operación: reiniciar servicios, restaurar respaldo, rotar credenciales",
              verifica: "Documento probado por alguien que no lo escribió" },
            { id: "devops.runbooks.incidentes", fuente: "reco",
              label: "Clasificación de incidentes por severidad y tiempo de respuesta comprometido",
              verifica: "Tabla de severidades acordada con el cliente y registro de incidentes con su tiempo real de atención" },
            { id: "devops.runbooks.postmortem", fuente: "reco",
              label: "Análisis posterior de cada incidente mayor, sin buscar culpables",
              verifica: "Reporte con causa raíz y acciones correctivas con responsable y fecha" },
            { id: "devops.runbooks.calendario", fuente: "reco",
              label: "Calendario de congelamiento en fechas críticas de recaudación",
              verifica: "Acuerdo de no desplegar en cierre de mes ni en pico de refrendo, salvo urgencia autorizada" },
          ],
        },
        {
          id: "devops.documentacion",
          nombre: "Documentación técnica viva",
          resumen: "Que la arquitectura no viva solo en la cabeza del equipo.",
          pregunta: "¿Un desarrollador nuevo puede levantar SIR Plus solo con la documentación?",
          checks: [
            { id: "devops.documentacion.arranque", fuente: "reco",
              label: "Guía de arranque local del proyecto, probada por alguien nuevo",
              verifica: "Cronómetro: cuánto tarda una persona nueva en tener el sistema corriendo" },
            { id: "devops.documentacion.arquitectura", fuente: "reco",
              label: "Diagrama de arquitectura actualizado con cada cambio estructural",
              verifica: "Fecha de última actualización del diagrama contra la fecha del último cambio de infraestructura" },
            { id: "devops.documentacion.decisiones", fuente: "reco",
              label: "Registro de decisiones técnicas y su porqué",
              verifica: "Bitácora breve por decisión relevante: contexto, opciones y elección" },
            { id: "devops.documentacion.funcional", fuente: "codigo",
              label: "Documentación funcional por módulo, en lenguaje no técnico",
              verifica: "Existe la Guía Funcional OPENSIR (Caja, Trámites, Padrones, Ley de Ingresos) elaborada desde el código. Falta su equivalente para SIR Plus / Jalisco" },
          ],
        },
      ],
    },
  ],
};

// ══════════════════════════════════════════════════════════════════════════════
// CAPA 3 — DEVSECOPS
// ══════════════════════════════════════════════════════════════════════════════

const DEVSECOPS: Capa = {
  id: "devsecops",
  nombre: "DevSecOps",
  sub: "Seguridad y datos personales desde el primer commit",
  descripcion:
    "SIR Plus maneja dinero público y datos personales de contribuyentes. Esta capa cubre cómo evitamos introducir vulnerabilidades, cómo protegemos la información y cómo demostramos que lo hacemos.",
  color: "#F43F5E",
  grupos: [
    {
      id: "sec-ciclo",
      nombre: "Seguridad en el ciclo de desarrollo",
      nodos: [
        {
          id: "sec.herramientas",
          nombre: "Herramientas de desarrollo seguro",
          resumen: "Análisis automático que revise el código y las dependencias en cada cambio.",
          pregunta: "¿Qué herramientas de desarrollo seguro estamos considerando?",
          checks: [
            { id: "sec.herramientas.sast", fuente: "reco",
              label: "Análisis estático de código en el pipeline (por ejemplo Semgrep o Bandit para Python)",
              verifica: "Reporte de hallazgos por severidad en cada ejecución y regla de bloqueo para severidad alta" },
            { id: "sec.herramientas.sca", fuente: "reco",
              label: "Análisis de dependencias con vulnerabilidades conocidas, en backend y frontend",
              verifica: "Reporte de dependencias vulnerables y política de actualización con plazo por severidad" },
            { id: "sec.herramientas.secretos", fuente: "reco",
              label: "Detección de credenciales filtradas en el repositorio y su historial",
              verifica: "Escaneo del historial completo, no solo de los cambios nuevos, y evidencia de rotación de lo encontrado" },
            { id: "sec.herramientas.dast", fuente: "reco",
              label: "Escaneo dinámico del portal ciudadano y del admin en ambiente de pruebas",
              verifica: "Reporte del escaneo con hallazgos cerrados o aceptados con justificación" },
            { id: "sec.herramientas.imagenes", fuente: "reco",
              label: "Escaneo de imágenes de contenedor antes de publicar",
              verifica: "Resultado del escaneo adjunto a cada liberación" },
            { id: "sec.herramientas.sbom", fuente: "reco",
              label: "Inventario de componentes de software del sistema",
              verifica: "Archivo de inventario generado por versión, útil para responder rápido ante una vulnerabilidad pública" },
          ],
        },
        {
          id: "sec.gestion",
          nombre: "Gestión de vulnerabilidades",
          resumen: "Que un hallazgo tenga dueño, plazo y cierre verificado.",
          pregunta: "¿Qué hacemos con lo que encontramos?",
          checks: [
            { id: "sec.gestion.registro", fuente: "zoho",
              label: "Registro único de vulnerabilidades con severidad, responsable y fecha compromiso",
              verifica: "Antecedente 'SIR Lite — vulnerabilidades detectadas'. Mismo tratamiento formal para SIR Plus" },
            { id: "sec.gestion.sla", fuente: "reco",
              label: "Plazos de remediación por severidad, acordados y medidos",
              verifica: "Reporte de vulnerabilidades abiertas fuera de plazo, revisado en la junta de operación" },
            { id: "sec.gestion.pentest", fuente: "reco",
              label: "Prueba de penetración antes de salir a producción con datos reales",
              verifica: "Informe de pentest con hallazgos cerrados y una prueba de re-verificación" },
            { id: "sec.gestion.divulgacion", fuente: "reco",
              label: "Canal para que el cliente o un tercero reporte una vulnerabilidad",
              verifica: "Correo o formulario publicado y procedimiento de atención documentado" },
          ],
        },
      ],
    },
    {
      id: "sec-app",
      nombre: "Seguridad de la aplicación",
      nodos: [
        {
          id: "sec.identidad",
          nombre: "Identidad y acceso",
          resumen: "Quién entra, con qué puede entrar y qué puede hacer adentro.",
          pregunta: "¿Un cajero puede hacer algo que no le corresponde?",
          checks: [
            { id: "sec.identidad.mfa", fuente: "zoho",
              label: "Autenticación en dos pasos para usuarios administrativos",
              verifica: "Tarea JAL 'Autenticación en dos pasos' (backend, en documentación). Evidencia del segundo factor exigido al menos a perfiles con jefatura" },
            { id: "sec.identidad.roles", fuente: "zoho",
              label: "Alta de usuarios, roles y permisos rediseñada, intuitiva y navegable",
              verifica: "Tarea JAL-SIR+ 'Rediseño UX/UI de alta de usuarios (CRUD), roles y permisos' — incluye que los permisos se creen automáticamente al agregar una funcionalidad nueva" },
            { id: "sec.identidad.permisos_post", fuente: "zoho",
              label: "Endpoint de permisos con alta habilitada, no solo consulta",
              verifica: "Tarea JAL-SIR+ 'Habilitar el POST a la tabla de permission' — hoy el endpoint solo tiene GET" },
            { id: "sec.identidad.granular", fuente: "zoho",
              label: "Control detallado por tipo de movimiento de padrón, más allá del permiso general",
              verifica: "Tarea JAL-SIR+ 'Control Detallado de CRUD/Padrones': catálogo configurador de movimientos permitidos por padrón y campo" },
            { id: "sec.identidad.privilegio", fuente: "reco",
              label: "Revisión periódica de quién tiene permisos elevados y baja inmediata al salir del proyecto",
              verifica: "Acta trimestral de revisión de accesos, firmada por el responsable del área" },
            { id: "sec.identidad.sesiones", fuente: "reco",
              label: "Expiración de sesión, cierre por inactividad y bloqueo por intentos fallidos",
              verifica: "Prueba funcional documentada de cada uno de los tres comportamientos" },
          ],
        },
        {
          id: "sec.auditoria",
          nombre: "Auditoría y trazabilidad",
          resumen: "Poder responder quién hizo qué, cuándo y desde dónde.",
          pregunta: "Si mañana hay una diferencia de dinero, ¿podemos demostrar qué pasó?",
          checks: [
            { id: "sec.auditoria.log", fuente: "zoho",
              label: "Bitácora de movimientos de padrones, catálogos y cartera",
              verifica: "Tarea JAL-SIR+ 'Auditoría/Log de Movimientos': registrar tabla afectada, id del registro, estado anterior y posterior, usuario y momento" },
            { id: "sec.auditoria.endpoints", fuente: "zoho",
              label: "Cada endpoint crítico mapeado a la acción auditable que representa",
              verifica: "Tarea 'aplica a todos los proyectos': quién y cuándo cambió propietarios de un predio, importes de cargo, pasos de trámite, configuración de tipos de cargo, o reimprimió una orden de pago" },
            { id: "sec.auditoria.seguridad", fuente: "zoho",
              label: "Cada acción de seguridad (permitir/restringir) queda registrada en el módulo de auditoría",
              verifica: "Requisito incluido en la tarea de rediseño de usuarios, roles y permisos" },
            { id: "sec.auditoria.inalterable", fuente: "reco",
              label: "Bitácora no editable ni borrable desde la aplicación, con retención definida",
              verifica: "Prueba de que ningún rol, ni el administrador, puede alterar un registro de auditoría" },
            { id: "sec.auditoria.consulta", fuente: "reco",
              label: "Consulta de auditoría usable por el cliente, no solo por un DBA",
              verifica: "Pantalla de consulta con filtros por usuario, fecha, padrón y tipo de movimiento" },
          ],
        },
        {
          id: "sec.aplicacion",
          nombre: "Endurecimiento de la aplicación",
          resumen: "Las defensas básicas de una aplicación web expuesta a internet.",
          pregunta: "¿Estamos cubiertos contra los ataques más comunes?",
          checks: [
            { id: "sec.aplicacion.owasp", fuente: "reco",
              label: "Revisión contra las diez vulnerabilidades más comunes de aplicaciones web (OWASP Top 10)",
              verifica: "Lista de verificación firmada por riesgo, con la prueba que lo descarta" },
            { id: "sec.aplicacion.portal", fuente: "zoho",
              label: "Portal ciudadano con captcha, límite de intentos y ofuscación de identificadores",
              verifica: "Antecedente REPUVE: refactorización de seguridad de login, captcha, rate limit y ofuscación de IDs. Confirmar que SIR Plus nace con esto" },
            { id: "sec.aplicacion.autorizacion", fuente: "reco",
              label: "Autorización verificada en el servidor en cada petición, no solo ocultando botones",
              verifica: "Prueba: llamar directo al endpoint con un usuario sin permiso y comprobar que responde denegado" },
            { id: "sec.aplicacion.entrada", fuente: "zoho",
              label: "Validación integral de datos antes de persistir",
              verifica: "Tarea 'aplica a todos los proyectos': validaciones integrales en backend para creación de órdenes de pago y estados de cuenta, para impedir órdenes con datos inconsistentes" },
            { id: "sec.aplicacion.archivos", fuente: "reco",
              label: "Carga de documentos con tipo y tamaño validados y análisis de contenido",
              verifica: "Prueba de que no se puede subir un ejecutable disfrazado de comprobante" },
            { id: "sec.aplicacion.cabeceras", fuente: "reco",
              label: "Cabeceras de seguridad y cookies protegidas en portal y admin",
              verifica: "Escaneo de cabeceras con resultado adjunto" },
          ],
        },
      ],
    },
    {
      id: "sec-datos",
      nombre: "Datos personales y cumplimiento",
      nodos: [
        {
          id: "sec.privacidad",
          nombre: "Marco legal de datos personales",
          resumen: "El SIR trata datos personales de contribuyentes por cuenta de una autoridad estatal.",
          pregunta: "¿Nos regimos por alguna ley de datos personales?",
          checks: [
            { id: "sec.privacidad.marco", fuente: "reco",
              label: "Determinar formalmente el marco aplicable: normativa mexicana de datos personales en posesión de sujetos obligados, más la ley estatal de Jalisco",
              verifica: "El Gobierno de Jalisco es sujeto obligado y SIGOB actúa como encargado del tratamiento. ESTE PUNTO DEBE VALIDARSE CON EL ÁREA JURÍDICA DEL CLIENTE — la normativa federal en la materia tuvo cambios recientes y no debe citarse de memoria" },
            { id: "sec.privacidad.contrato", fuente: "reco",
              label: "Cláusula o convenio de encargado del tratamiento entre SIGOB y el cliente",
              verifica: "Instrumento jurídico firmado que delimite qué puede hacer SIGOB con los datos y por cuánto tiempo" },
            { id: "sec.privacidad.aviso", fuente: "codigo",
              label: "Aviso de privacidad publicado en el portal y vigente",
              verifica: "En Ventanilla Única el aviso de privacidad es contenido institucional obligatorio. Confirmar versión, fecha y que corresponda al tratamiento real" },
            { id: "sec.privacidad.derechos", fuente: "reco",
              label: "Procedimiento para atender solicitudes de acceso, rectificación, cancelación y oposición",
              verifica: "Flujo documentado con tiempos de respuesta y responsable del lado del cliente" },
            { id: "sec.privacidad.inventario", fuente: "reco",
              label: "Inventario de datos personales por módulo: qué se recolecta, para qué y cuánto se conserva",
              verifica: "Tabla por padrón y trámite con finalidad y plazo de conservación" },
          ],
        },
        {
          id: "sec.proteccion",
          nombre: "Protección efectiva de los datos",
          resumen: "Medidas técnicas concretas, más allá del documento legal.",
          pregunta: "Si alguien obtiene una copia de la base, ¿qué se lleva?",
          checks: [
            { id: "sec.proteccion.minimizacion", fuente: "reco",
              label: "Minimización: no pedir ni mostrar datos que el trámite no necesita",
              verifica: "Revisión campo por campo de los formularios del portal contra el requisito legal del trámite" },
            { id: "sec.proteccion.cifrado", fuente: "reco",
              label: "Cifrado en tránsito en todos los canales y en reposo en base y respaldos",
              verifica: "Escaneo TLS de cada dominio y evidencia de cifrado de respaldos y buckets" },
            { id: "sec.proteccion.enmascarado", fuente: "reco",
              label: "Enmascaramiento de datos sensibles en pantallas y en reportes exportables",
              verifica: "Revisión de qué ve un usuario de ventanilla frente a uno de jefatura" },
            { id: "sec.proteccion.no_prod", fuente: "reco",
              label: "Prohibición efectiva de usar datos reales en desarrollo y pruebas",
              verifica: "Riesgo frecuente y de alto impacto. Procedimiento de anonimización y auditoría de las bases de QA" },
            { id: "sec.proteccion.accesos", fuente: "reco",
              label: "Bitácora de consulta de datos personales, no solo de modificación",
              verifica: "Registro de quién consultó el expediente de un contribuyente, requisito habitual en auditorías" },
            { id: "sec.proteccion.brecha", fuente: "reco",
              label: "Protocolo de notificación de brecha de datos personales",
              verifica: "Procedimiento con plazos y responsables, validado con el área jurídica del cliente" },
          ],
        },
        {
          id: "sec.reco",
          nombre: "Lo que recomiendo añadir a esta capa",
          resumen: "Prácticas que elevan el nivel sin costo desproporcionado.",
          pregunta: "¿Qué más deberíamos poner en la capa de DevSecOps?",
          checks: [
            { id: "sec.reco.modelado", fuente: "reco",
              label: "Modelado de amenazas por módulo crítico (Caja, pagos en línea, permisos)",
              verifica: "Sesión de una hora por módulo con hallazgos convertidos en tareas" },
            { id: "sec.reco.capacitacion", fuente: "reco",
              label: "Capacitación de desarrollo seguro para el equipo, con registro de asistencia",
              verifica: "Constancia por persona y refuerzo anual" },
            { id: "sec.reco.definicion", fuente: "reco",
              label: "Criterios de seguridad dentro de la definición de terminado de cada tarea",
              verifica: "Plantilla de tarea que exija indicar impacto en datos personales y en permisos" },
            { id: "sec.reco.terceros", fuente: "reco",
              label: "Evaluación de seguridad de proveedores externos (pasarela, timbrado, hospedaje)",
              verifica: "Cuestionario por proveedor y revisión de sus certificaciones vigentes" },
            { id: "sec.reco.llaves", fuente: "reco",
              label: "Rotación periódica de credenciales, llaves y tokens de integración",
              verifica: "Calendario de rotación y bitácora de la última rotación por sistema" },
            { id: "sec.reco.continuidad", fuente: "reco",
              label: "Ejercicio anual de respuesta a incidente de seguridad, distinto al de recuperación técnica",
              verifica: "Reporte del simulacro con tiempos de detección, contención y comunicación" },
          ],
        },
      ],
    },
  ],
};

// ══════════════════════════════════════════════════════════════════════════════
// CAPA 4 — SISTEMA SIR PLUS
// ══════════════════════════════════════════════════════════════════════════════

const SISTEMA: Capa = {
  id: "sistema",
  nombre: "Sistema",
  sub: "Admin · Portal Financiero (Ventanilla Única) · RETYS",
  descripcion:
    "Los tres canales del sistema y los módulos que los sostienen. Cada módulo lista lo que hay que reforzar y verificar, y con qué evidencia se documenta.",
  color: "#C9A84C",
  grupos: [
    {
      id: "sis-admin",
      nombre: "ADMIN — back-office de recaudación",
      nodos: [
        {
          id: "sis.admin.ley",
          nombre: "Ley de Ingresos",
          resumen: "El motor de reglas fiscales: periodos, tipos de cargo, tarifas, recargos, gastos, descuentos, actualizaciones y alertas. Es la base de la que dependen todos los demás módulos.",
          pregunta: "¿La regla que configuramos es la que realmente se cobra?",
          checks: [
            { id: "sis.admin.ley.periodo", fuente: "codigo",
              label: "Periodo fiscal único vigente, y periodos autorizados o cancelados que ya no se pueden borrar",
              verifica: "Prueba de que no existen dos periodos vigentes y de que un periodo autorizado es intocable" },
            { id: "sis.admin.ley.calculo", fuente: "zoho",
              label: "Cálculo verificado de recargos, actualizaciones, gastos y descuentos contra la Ley de Ingresos de Jalisco",
              verifica: "Es la falla más recurrente del SIR en otras entidades (recargos mal calculados, multa que no aparece en vista previa). Matriz de casos con resultado esperado, validada por el cliente" },
            { id: "sis.admin.ley.tipo_cargo", fuente: "codigo",
              label: "Tipo de cargo como regla central: padrón al que aplica y sus descuentos, recargos, gastos, multas, accesorios y actualizaciones asociados",
              verifica: "Documentación de procesos del sistema. Ficha por tipo de cargo de Jalisco con todos sus accesorios configurados, validada contra la Ley de Ingresos" },
            { id: "sis.admin.ley.recargo_multa", fuente: "codigo",
              label: "Distinción explícita entre recargo normal y multa en los tipos de recargo",
              verifica: "Documentación de procesos del sistema. Casos de prueba que comprueben el tratamiento distinto de ambos en el cálculo y en el recibo" },
            { id: "sis.admin.ley.tarifas", fuente: "codigo",
              label: "Catálogo de tarifas por tramos y su vínculo con cada tipo de cargo",
              verifica: "Pruebas en los límites de cada tramo, que es donde se rompen los cálculos" },
            { id: "sis.admin.ley.uma", fuente: "zoho",
              label: "Actualización masiva de cartera al cambiar UMA anual o INPC mensual",
              verifica: "Tarea JAL-SIR+ 'Actualización/Persistencia Masiva de Cartera'. Procedimiento con respaldo previo, medición de tiempo y cuadre posterior" },
            { id: "sis.admin.ley.autorizacion", fuente: "codigo",
              label: "Descuentos que requieren autorización pasan por su flujo y quedan registrados",
              verifica: "El sistema define descuentos con autorización y pantalla de 'Descuentos por Revisar'. Prueba del flujo completo con dos usuarios distintos" },
            { id: "sis.admin.ley.alertas", fuente: "codigo",
              label: "Alertas restrictivas que efectivamente bloquean cobro y trámite",
              verifica: "Prueba: padrón con alerta restrictiva no debe poder pagar ni tramitar en ninguno de los tres canales" },
          ],
        },
        {
          id: "sis.admin.padrones",
          nombre: "Padrones",
          resumen: "El registro de quién y qué tiene obligaciones: contribuyentes, empresas, predios, vehículos, permisos e infracciones.",
          pregunta: "¿El padrón es único, confiable y trazable?",
          checks: [
            { id: "sis.admin.padrones.contribuyente", fuente: "zoho",
              label: "Solo Contribuyente: eliminar la figura de Ciudadano en todos los canales",
              verifica: "Tarea JAL-SIR+ 'Solo Contribuyente (sin Ciudadano)'. Revisión de que ningún canal ni catálogo siga referenciando la tabla de Ciudadano" },
            { id: "sis.admin.padrones.considerado", fuente: "zoho",
              label: "Contribuyente considerado (jubilado, pensionado) con sus descuentos, basado en Contribuyente",
              verifica: "Tarea JAL-SIR+ y su equivalente marcada 'aplica a todos los proyectos'. Prueba en tipos de cargo, recargo, gasto, actualización y descuento" },
            { id: "sis.admin.padrones.nuevos", fuente: "zoho",
              label: "Padrones nuevos de Jalisco: estacionómetros, multas administrativas no fiscales, hipotecas, billetes de depósito",
              verifica: "Cuatro tareas JAL-SIR+ con su tabla fuente Informix identificada. Cuadre de registros migrados por padrón" },
            { id: "sis.admin.padrones.movimientos", fuente: "zoho",
              label: "Catálogo configurable de tipos de movimiento por padrón, con control de qué campos se pueden cambiar",
              verifica: "Tarea JAL-SIR+ 'Control Detallado de CRUD/Padrones'. Cada cambio permitido debe quedar registrado en la bitácora de auditoría" },
            { id: "sis.admin.padrones.via_tramite", fuente: "codigo",
              label: "La información sensible del padrón solo se modifica a través de un trámite, no por edición directa",
              verifica: "Documentación de procesos del sistema: gran parte de la información del padrón está vinculada a cargos, trámites, convenios, órdenes y recibos. Definir campo por campo qué es editable y qué exige trámite, y probar que la edición directa está bloqueada" },
            { id: "sis.admin.padrones.duplicados", fuente: "reco",
              label: "Prevención de duplicados y criterio único de identificación del contribuyente",
              verifica: "Reporte de posibles duplicados por RFC/CURP y nombre, ejecutado antes y después de la migración" },
            { id: "sis.admin.padrones.vehicular", fuente: "codigo",
              label: "Ecosistema vehicular: vehículo, motocicleta, remolque, propietario y tarjeta de circulación",
              verifica: "Prueba del ciclo completo: alta con asignación de placa, cambio de propietario, baja con liberación de placa y refrendo" },
          ],
        },
        {
          id: "sis.admin.caja",
          nombre: "Caja y cortes",
          resumen: "Consulta del contribuyente y su padrón, cálculo del adeudo, generación de la orden de pago y cobro: presencial, con o sin convenio.",
          pregunta: "¿Lo que cobra la ventanilla cuadra al centavo con lo que reporta el sistema?",
          checks: [
            { id: "sis.admin.caja.consulta", fuente: "codigo",
              label: "Consulta del contribuyente por clave única (RFC, clave de padrón o CURP) y de sus padrones relacionados",
              verifica: "Documentación de procesos del sistema. Casos de prueba con cada tipo de clave, incluyendo contribuyente con varios padrones" },
            { id: "sis.admin.caja.adeudo", fuente: "codigo",
              label: "Consulta de adeudo con y sin recálculo, segmentada por cargos, sistemas, trámites, convenios y obligaciones",
              verifica: "Documentación de procesos del sistema. Contraste del adeudo con recálculo contra el sin recálculo, y definición de cuándo se usa cada uno" },
            { id: "sis.admin.caja.referencias", fuente: "codigo",
              label: "Orden de pago con referencias pagables por cada institución con la que exista convenio",
              verifica: "Documentación de procesos del sistema. Prueba de generación de referencia por cada convenio bancario contratado por Jalisco, y de su aplicación al pagarse" },
            { id: "sis.admin.caja.corte", fuente: "codigo",
              label: "Corte obligatorio: sin corte abierto no hay cobro, y al cierre cuadra lo recaudado",
              verifica: "Prueba de que el botón de pago queda deshabilitado sin corte, y cuadre de un turno completo" },
            { id: "sis.admin.caja.metodos", fuente: "codigo",
              label: "Métodos de pago combinables: efectivo, tarjeta, depósito en garantía, terminal electrónica y transferencia",
              verifica: "Casos de prueba con pagos mixtos, incluyendo cálculo de cambio" },
            { id: "sis.admin.caja.recibos", fuente: "zoho",
              label: "Un pago, un recibo, con el importe correcto",
              verifica: "Historial en Nayarit: recibos duplicados al procesar pagos externos, recibos en línea con cantidad incorrecta, diferencia de monto al reimprimir. Prueba de idempotencia y de reimpresión" },
            { id: "sis.admin.caja.convenios", fuente: "codigo",
              label: "Convenios y parcialidades: anticipo, calendario de pagos y control de lo pendiente",
              verifica: "Prueba del ciclo completo, incluyendo cobro de parcialidades posteriores y cancelación del convenio" },
            { id: "sis.admin.caja.cfdi", fuente: "reco",
              label: "Facturación electrónica del pago con datos fiscales completos",
              verifica: "Timbrado de prueba en cada ambiente, con validación del comprobante y su cancelación" },
            { id: "sis.admin.caja.depositos", fuente: "codigo",
              label: "Depósitos bancarios y depósitos en garantía conciliados",
              verifica: "Bitácora de depósitos con banco, cuenta, importe y corte, contrastada contra el estado de cuenta" },
          ],
        },
        {
          id: "sis.admin.cartera",
          nombre: "Cartera (adeudos y pagos)",
          resumen: "El saldo vivo de cada contribuyente: lo que debe, lo que pagó y lo que se le condonó.",
          pregunta: "¿El adeudo que ve el ciudadano es el mismo que ve la ventanilla y el mismo que reporta contabilidad?",
          checks: [
            { id: "sis.admin.cartera.persistencia", fuente: "zoho",
              label: "Cálculo y persistencia correcta de adeudos y su actualización al generar o cancelar pagos",
              verifica: "Tarea JAL-SIR+ 'Control de Cartera (Adeudos y Pagos) y su persistencia': cargos, recargos, actualizaciones, gastos y descuentos contra recibos y abonos, con y sin convenio" },
            { id: "sis.admin.cartera.consistencia", fuente: "zoho",
              label: "Consistencia entre canales: mismo adeudo en admin, portal y RETYS",
              verifica: "Prueba cruzada sobre el mismo contribuyente en los tres canales, el mismo día y a la misma hora" },
            { id: "sis.admin.cartera.orden", fuente: "zoho",
              label: "Orden de pago que muestre lo mismo al generarse y al reimprimirse",
              verifica: "Tareas 'aplica a todos los proyectos': mostrar el desglose desde el JSON de cargos referenciados, y consistencia de recargos y estatus saldado en la reimpresión" },
            { id: "sis.admin.cartera.bloqueos", fuente: "zoho",
              label: "Cargos originados en trámites, infracciones y declaraciones bloqueados en el módulo de cargos",
              verifica: "Tarea 'aplica a todos los proyectos' ya trabajada en Oaxaca. Confirmar que SIR Plus nace con ese bloqueo" },
            { id: "sis.admin.cartera.cuadre", fuente: "reco",
              label: "Reporte diario de cuadre contable, ejecutado desde el día uno de producción",
              verifica: "Aprendizaje de Nayarit, donde el descuadre se detectó tarde. Reporte con diferencia esperada en cero y responsable de revisarlo" },
          ],
        },
        {
          id: "sis.admin.inventarios",
          nombre: "Inventarios y formas valoradas",
          resumen: "Control físico de placas y documentos con valor, por unidad recaudadora y por usuario.",
          pregunta: "¿Sabemos dónde está cada placa y cada forma valorada?",
          checks: [
            { id: "sis.admin.inventarios.placas", fuente: "zoho",
              label: "Inventario y asignación de placas vehiculares por unidad recaudadora y usuario",
              verifica: "Tarea JAL-SIR+ 'Inventario/Almacén y Control de Asignación de Placas Vehiculares'. Prueba de alta, asignación con pago y baja" },
            { id: "sis.admin.inventarios.formas", fuente: "zoho",
              label: "Inventario de formas valoradas (documentos de imprenta) con asignación y pago",
              verifica: "Tarea JAL-SIR+ 'Inventario/Almacén y Control de Asignación de Formas Valoradas'" },
            { id: "sis.admin.inventarios.conciliacion", fuente: "reco",
              label: "Conciliación física contra sistema, con responsable por unidad",
              verifica: "Acta de inventario físico periódica y reporte de faltantes" },
            { id: "sis.admin.inventarios.trazabilidad", fuente: "reco",
              label: "Trazabilidad de cada folio: de la imprenta al contribuyente",
              verifica: "Consulta que muestre el ciclo de vida completo de un folio" },
          ],
        },
        {
          id: "sis.admin.pae",
          nombre: "PAE — ejecución fiscal",
          resumen: "Cobranza coactiva: requerimientos, vigilancia de obligaciones y cartera vencida.",
          pregunta: "¿La cartera vencida se representa correctamente y el requerimiento es legalmente válido?",
          checks: [
            { id: "sis.admin.pae.personalizacion", fuente: "zoho",
              label: "Emisión de requerimientos y vigilancia de obligaciones conforme a Jalisco",
              verifica: "Tarea JAL-SIR+ 'PAE Ejecución Fiscal', con tabla fuente Informix 'notificacion'. Validación jurídica del formato del requerimiento" },
            { id: "sis.admin.pae.cartera", fuente: "zoho",
              label: "Representación correcta de los cargos de cartera vencida",
              verifica: "Antecedente en Nayarit donde el PAE no representaba bien la cartera vencida. Casos de prueba con antigüedad de saldos" },
            { id: "sis.admin.pae.notificacion", fuente: "reco",
              label: "Trazabilidad de la notificación: cuándo se emitió, a quién y con qué acuse",
              verifica: "Expediente digital por requerimiento con su acuse asociado" },
            { id: "sis.admin.pae.gastos", fuente: "codigo",
              label: "Gastos de ejecución y notificación calculados según su tipo configurado",
              verifica: "Casos de prueba de gastos aplicados sobre cargos concretos" },
          ],
        },
        {
          id: "sis.admin.bi",
          nombre: "Reporteador y BI",
          resumen: "Los reportes de los que dependen contabilidad, tesorería y la toma de decisiones.",
          pregunta: "¿Los reportes son confiables y no tumban al sistema?",
          checks: [
            { id: "sis.admin.bi.tableros", fuente: "zoho",
              label: "Configuración de BI y tableros para Jalisco",
              verifica: "Tarea JAL-SIR+ 'Configuración BI y Tableros' (base de datos, en pruebas internas). Catálogo de tableros acordado con el cliente" },
            { id: "sis.admin.bi.catalogo", fuente: "reco",
              label: "Catálogo de reportes con su definición de negocio y responsable",
              verifica: "Ficha por reporte: qué cuenta, con qué filtros y con qué fuente. Evita el reporte que 'no cuadra' por definiciones distintas" },
            { id: "sis.admin.bi.homologacion", fuente: "zoho",
              label: "Homologación de criterios entre reportes (por ejemplo, fecha del recibo)",
              verifica: "Antecedente en Nayarit: homologar reportes por fecha del recibo. Prueba de que dos reportes del mismo periodo dan el mismo total" },
            { id: "sis.admin.bi.aislamiento", fuente: "zoho",
              label: "Reportes pesados sin afectar la operación de ventanilla",
              verifica: "Antecedente: caídas constantes del reporteador tras actualización. Ejecución contra réplica de lectura y prueba en horario pico" },
            { id: "sis.admin.bi.coordinados", fuente: "zoho",
              label: "Ingresos coordinados",
              verifica: "Tarea JAL-SIR+ 'Ingresos Coordinados'. Definición de reglas de participación y reporte de distribución" },
          ],
        },
      ],
    },
    {
      id: "sis-portal",
      nombre: "PORTAL FINANCIERO / VENTANILLA ÚNICA — canal ciudadano",
      nodos: [
        {
          id: "sis.portal.adeudos",
          nombre: "Consulta de adeudos y orden de pago",
          resumen: "El ciudadano identifica lo que debe y obtiene su referencia para pagar.",
          pregunta: "¿El ciudadano ve su adeudo correcto y puede pagarlo sin ir a ventanilla?",
          checks: [
            { id: "sis.portal.adeudos.busqueda", fuente: "codigo",
              label: "Búsqueda por padrón: predial, vehicular, licencias y demás conceptos, con recargos incluidos",
              verifica: "Casos de prueba por padrón, contrastando el monto con el que arroja Caja" },
            { id: "sis.portal.adeudos.orden", fuente: "codigo",
              label: "Orden de pago que agrupe varios cargos en una sola referencia bancaria",
              verifica: "Prueba de generación, pago y aplicación automática de la referencia" },
            { id: "sis.portal.adeudos.linea", fuente: "zoho",
              label: "Línea de captura válida para banco y tiendas de conveniencia",
              verifica: "Antecedente en Nayarit: no salía la línea de captura del convenio con tiendas. Prueba con cada convenio bancario contratado por Jalisco" },
            { id: "sis.portal.adeudos.vigencia", fuente: "reco",
              label: "Vigencia de la referencia y recálculo al vencer",
              verifica: "Prueba de que una referencia vencida no se puede pagar con un monto desactualizado" },
          ],
        },
        {
          id: "sis.portal.pagos",
          nombre: "Pago en línea",
          resumen: "El momento donde entra el dinero. Es el punto de mayor riesgo del portal.",
          pregunta: "¿Puede perderse o duplicarse un pago?",
          checks: [
            { id: "sis.portal.pagos.pasarela", fuente: "codigo",
              label: "Pasarela de pago operando en pruebas y en producción, con credenciales separadas",
              verifica: "Antecedente en Nayarit: no se podían hacer pagos en línea en el portal de pruebas. Prueba de extremo a extremo en cada ambiente" },
            { id: "sis.portal.pagos.idempotencia", fuente: "zoho",
              label: "Un cobro no se aplica dos veces aunque el banco confirme dos veces",
              verifica: "Antecedente: pagos externos que generaron dos recibos. Prueba de doble notificación del proveedor" },
            { id: "sis.portal.pagos.conciliacion", fuente: "zoho",
              label: "Conciliación diaria de pagos en línea contra el reporte del proveedor",
              verifica: "Antecedente de descuadres. Reporte automático de pagos sin aplicar y aplicados sin cobro" },
            { id: "sis.portal.pagos.recibo", fuente: "zoho",
              label: "Recibo del pago en línea con el importe exacto y disponible de inmediato",
              verifica: "Antecedente: recibos por pago en línea con cantidad incorrecta. Casos de prueba con descuentos y recargos aplicados" },
            { id: "sis.portal.pagos.interrumpido", fuente: "reco",
              label: "Comportamiento definido si el ciudadano cierra el navegador a media transacción",
              verifica: "Prueba de transacción interrumpida y estado final del cargo" },
          ],
        },
        {
          id: "sis.portal.cuenta",
          nombre: "Cuenta del contribuyente",
          resumen: "Expediente digital: sus datos, sus bienes, su historial y sus notificaciones.",
          pregunta: "¿El expediente digital es completo y seguro?",
          checks: [
            { id: "sis.portal.cuenta.acceso", fuente: "codigo",
              label: "Ingreso validado por código de verificación, sin contraseña fija",
              verifica: "Mecanismo usado en Ventanilla Única. Prueba de expiración del código, límite de reenvíos y bloqueo por intentos" },
            { id: "sis.portal.cuenta.datos", fuente: "codigo",
              label: "Datos generales capturados una sola vez y reutilizables en trámites y pagos",
              verifica: "Prueba de que actualizar un dato se refleja en trámites en curso" },
            { id: "sis.portal.cuenta.historial", fuente: "codigo",
              label: "Historial de trámites, pagos y declaraciones, con sus comprobantes",
              verifica: "Contraste del historial del portal contra los registros del admin" },
            { id: "sis.portal.cuenta.buzon", fuente: "codigo",
              label: "Buzón de notificaciones oficiales y constancias emitidas",
              verifica: "Prueba de entrega y acuse de una notificación, con valor probatorio definido con el cliente" },
            { id: "sis.portal.cuenta.privacidad", fuente: "reco",
              label: "Un contribuyente solo puede ver su propia información",
              verifica: "Prueba de acceso directo con el identificador de otro contribuyente: debe ser denegado" },
          ],
        },
        {
          id: "sis.portal.servicios",
          nombre: "Facturación, citas, quejas y contenido",
          resumen: "Los servicios que completan la relación del ciudadano con la autoridad.",
          pregunta: "¿El portal resuelve el trámite completo o obliga a ir a la oficina?",
          checks: [
            { id: "sis.portal.servicios.cfdi", fuente: "codigo",
              label: "Facturación electrónica de un pago ya realizado, con RFC, régimen y uso del comprobante",
              verifica: "Timbrado de prueba y validación del comprobante ante el proveedor autorizado" },
            { id: "sis.portal.servicios.citas", fuente: "zoho",
              label: "Agenda de citas con requisitos previos, confirmación y cancelación",
              verifica: "Tarea JAL-SIR+ 'Citas'. Prueba del ciclo completo y control de cupo por oficina" },
            { id: "sis.portal.servicios.quejas", fuente: "codigo",
              label: "Quejas con folio de seguimiento y evidencia adjunta",
              verifica: "Prueba de presentación, consulta por folio y resguardo de la evidencia" },
            { id: "sis.portal.servicios.oficinas", fuente: "codigo",
              label: "Directorio geolocalizado de oficinas con horarios vigentes",
              verifica: "Contraste del directorio contra la información oficial del cliente, con fecha de última actualización" },
            { id: "sis.portal.servicios.institucional", fuente: "codigo",
              label: "Contenido institucional: aviso de privacidad, normateca, noticias y guía del portal",
              verifica: "Responsable nombrado para mantenerlo vigente y fecha de última revisión visible" },
            { id: "sis.portal.servicios.accesibilidad", fuente: "reco",
              label: "Accesibilidad y uso en teléfono móvil, que es como entra la mayoría de la ciudadanía",
              verifica: "Prueba en dispositivos reales y revisión de contraste y navegación por teclado" },
          ],
        },
      ],
    },
    {
      id: "sis-retys",
      nombre: "RETYS — trámites y servicios",
      nodos: [
        {
          id: "sis.retys.gpm",
          nombre: "GPM — motor genérico de trámites",
          resumen: "El módulo más grande: un motor configurable que sirve para predios, empresas, licencias, alcoholes, hospedaje, nómina y más, según su plantilla.",
          pregunta: "¿Un trámite nuevo se configura, o hay que programarlo?",
          checks: [
            { id: "sis.retys.gpm.plantillas", fuente: "codigo",
              label: "Plantilla por tipo de trámite con sus pasos (validación, requisitos, cargos, firma, GIS, cita, documentos)",
              verifica: "Documentar la plantilla de cada trámite de Jalisco y probar que agregar uno nuevo no requiere código" },
            { id: "sis.retys.gpm.padrones", fuente: "codigo",
              label: "Configuración de campos por tipo de padrón: qué se muestra, qué es obligatorio, qué se oculta",
              verifica: "Matriz de campos por padrón validada con el cliente antes de configurar" },
            { id: "sis.retys.gpm.cualquier_padron", fuente: "codigo",
              label: "Cualquier padrón puede originar un trámite",
              verifica: "Documentación de procesos del sistema. Matriz padrón × trámites disponibles, incluyendo los padrones nuevos de Jalisco" },
            { id: "sis.retys.gpm.cargos", fuente: "reco",
              label: "Generación y cobro de cargos del trámite con la regla vigente de Ley de Ingresos",
              verifica: "Prueba cruzada: mismo trámite cobrado por RETYS y por Caja debe dar el mismo importe" },
            { id: "sis.retys.gpm.estados", fuente: "zoho",
              label: "Trazabilidad de quién cambió el paso de un trámite y cuándo",
              verifica: "Tarea 'aplica a todos los proyectos' sobre auditoría de procesos prioritarios. Prueba de consulta de la bitácora del trámite" },
            { id: "sis.retys.gpm.declaraciones", fuente: "zoho",
              label: "Declaraciones empresariales como módulo con control documental",
              verifica: "Tarea JAL-SIR+ 'Declaraciones empresariales en Declaraciones (Control DOCUMENTAL)', estilo GPM Trámites" },
            { id: "sis.retys.gpm.requisitos", fuente: "codigo",
              label: "Ficha de requisitos, costo y tiempo de resolución visible antes de iniciar",
              verifica: "Contraste contra el catálogo oficial de trámites del estado" },
          ],
        },
        {
          id: "sis.retys.vehicular",
          nombre: "Trámites vehiculares",
          resumen: "Alta, baja, cambio de propietario y refrendo, con sus variantes por tipo de vehículo y de propietario.",
          pregunta: "¿El trámite vehicular de Jalisco es configurable o está amarrado a otra entidad?",
          checks: [
            { id: "sis.retys.vehicular.gpm", fuente: "zoho",
              label: "Migrar los trámites vehiculares al motor configurable (GPM Vehicular)",
              verifica: "Tarea JAL-SIR+ 'Trámites vehiculares en GPM - Vehicular'. Riesgo conocido: hoy el wizard vehicular está condicionado a la entidad Nayarit" },
            { id: "sis.retys.vehicular.movimientos", fuente: "codigo",
              label: "Los cuatro movimientos completos: alta con placa, baja con liberación, cambio y refrendo",
              verifica: "Casos de prueba por combinación de tipo de vehículo y tipo de propietario" },
            { id: "sis.retys.vehicular.placas", fuente: "zoho",
              label: "Asignación de placa ligada al inventario y al pago correspondiente",
              verifica: "Integración con el módulo de inventario de placas. Prueba de que no se asigna una placa sin pago ni sin existencia" },
            { id: "sis.retys.vehicular.tarjeta", fuente: "zoho",
              label: "Emisión y reimpresión de tarjeta de circulación",
              verifica: "Antecedente en Nayarit: error 400 al generar tarjeta de circulación. Prueba de emisión, reimpresión y validación del documento" },
            { id: "sis.retys.vehicular.descuentos", fuente: "zoho",
              label: "Descuentos y actualizaciones aplicados solo a los padrones que corresponde",
              verifica: "Antecedente en Nayarit: descuentos de motos aplicados a vehículos. Prueba por tipo de padrón vehicular" },
          ],
        },
        {
          id: "sis.retys.documental",
          nombre: "Documentos y firma",
          resumen: "Lo que el ciudadano entrega y lo que el sistema emite con validez.",
          pregunta: "¿El documento que emitimos es verificable y el que recibimos está resguardado?",
          checks: [
            { id: "sis.retys.documental.carga", fuente: "zoho",
              label: "Carga de requisitos en orden y su visualización correcta",
              verifica: "Antecedente en Nayarit: error al visualizar requisitos cargados. Prueba con distintos formatos y tamaños de archivo" },
            { id: "sis.retys.documental.firma", fuente: "codigo",
              label: "Firma electrónica en los trámites que la requieren",
              verifica: "Prueba de firma y validación posterior del documento firmado" },
            { id: "sis.retys.documental.verificacion", fuente: "codigo",
              label: "Verificación pública del documento emitido (código o folio consultable)",
              verifica: "Prueba de que un tercero puede validar la autenticidad de una constancia" },
            { id: "sis.retys.documental.resguardo", fuente: "reco",
              label: "Resguardo del expediente con su plazo de conservación",
              verifica: "Política de retención por tipo de trámite, alineada con el aviso de privacidad" },
          ],
        },
        {
          id: "sis.retys.seguimiento",
          nombre: "Seguimiento y cancelación",
          resumen: "El ciudadano debe poder saber en qué va su trámite y desistir si ya no procede.",
          pregunta: "¿El ciudadano puede seguir su trámite sin llamar por teléfono?",
          checks: [
            { id: "sis.retys.seguimiento.estado", fuente: "codigo",
              label: "Consulta del avance del trámite iniciado, con etapa y siguiente paso",
              verifica: "Prueba desde el portal con un trámite en curso" },
            { id: "sis.retys.seguimiento.cancelacion", fuente: "codigo",
              label: "Cancelación del trámite y su efecto sobre los cargos ya generados",
              verifica: "Prueba de cancelación con cargo pagado y con cargo no pagado: definir y documentar el comportamiento esperado" },
            { id: "sis.retys.seguimiento.notificacion", fuente: "reco",
              label: "Notificación al ciudadano en cada cambio de etapa",
              verifica: "Prueba de envío y registro de la notificación en el buzón" },
            { id: "sis.retys.seguimiento.tiempos", fuente: "reco",
              label: "Medición de tiempos reales de resolución por tipo de trámite",
              verifica: "Reporte de tiempo promedio contra el tiempo comprometido en la ficha del trámite" },
          ],
        },
      ],
    },
    {
      id: "sis-herencia",
      nombre: "Deuda técnica heredada — hallazgos del portal actual",
      nodos: [
        {
          id: "sis.herencia.pasarela",
          nombre: "Integración de la pasarela de pago",
          resumen: "En el portal actual el cobro con tarjeta no usa una integración limpia: el script de la pasarela se inyecta en el HTML base, expone un botón oculto con atributos data-* que el flujo llena por código y dispara con un clic programático, y un observador del DOM vigila cuándo aparece el bloque de «pago exitoso» para confirmar. El resultado se guarda en localStorage para que otro script lo lea después.",
          pregunta: "¿SIR Plus va a heredar esta integración o se rehace?",
          checks: [
            { id: "sis.herencia.pasarela.rehacer", fuente: "codigo",
              label: "Decidir explícitamente si la integración de pago se rehace en SIR Plus",
              verifica: "Decisión documentada. Un cobro que depende de que aparezca un bloque en el DOM se rompe con cualquier cambio del proveedor, sin aviso y sin error visible" },
            { id: "sis.herencia.pasarela.servidor", fuente: "reco",
              label: "Confirmación del pago validada en el servidor, no en el navegador",
              verifica: "El resultado debe llegar por notificación del proveedor al backend y comprobarse contra su API, no leerse del DOM ni de localStorage" },
            { id: "sis.herencia.pasarela.local", fuente: "codigo",
              label: "Sacar el resultado del cobro de localStorage",
              verifica: "Prueba: manipular el valor en localStorage no debe poder marcar un cobro como exitoso" },
            { id: "sis.herencia.pasarela.webview", fuente: "codigo",
              label: "Ruta oculta de pago dentro del WebView de la app móvil documentada y probada",
              verifica: "En el portal actual existe /pago-webview, que comunica el resultado a la app nativa por postMessage. Definir si aplica a Jalisco y probarla explícitamente" },
          ],
        },
        {
          id: "sis.herencia.config",
          nombre: "Configuración muerta y valores fijos en código",
          resumen: "El portal actual arrastra configuración que solo aplica a otra entidad y decisiones escritas directamente en el código.",
          pregunta: "¿Qué se está arrastrando de otras entidades sin que aplique a Jalisco?",
          checks: [
            { id: "sis.herencia.config.gis", fuente: "codigo",
              label: "Paso GIS con configuración geográfica que solo existe para Ciudad Juárez",
              verifica: "En el despliegue actual ese paso es inalcanzable fuera de esa entidad. Definir si Jalisco necesita GIS y, si sí, su configuración propia" },
            { id: "sis.herencia.config.tramite_fijo", fuente: "codigo",
              label: "Identificador de trámite escrito fijo en el código de la cuenta del contribuyente",
              verifica: "Cuando el registro está apenas «Ingresado», el portal invita a completar un trámite específico con ID fijo. Debe volverse configuración por entidad" },
            { id: "sis.herencia.config.deshabilitados", fuente: "codigo",
              label: "Módulos que existen en el código pero están deshabilitados (buzón y protestas en la cuenta)",
              verifica: "Decidir por módulo: se habilita para Jalisco, se completa o se retira. Código muerto en producción es superficie de riesgo" },
            { id: "sis.herencia.config.bandera", fuente: "codigo",
              label: "Bandera global que decide si se opera contra ciudadano o contra contribuyente",
              verifica: "La usan trámites, citas, quejas y cuenta a la vez. Es el mecanismo que toca la tarea JAL-SIR+ «Solo Contribuyente»: hay que rastrear todos sus usos antes de eliminar la figura de Ciudadano" },
            { id: "sis.herencia.config.entidad", fuente: "codigo",
              label: "Funcionalidad condicionada al nombre de la entidad",
              verifica: "El asistente vehicular no aparece si la instalación no es Nayarit. Buscar todas las condiciones por entidad y convertirlas en configuración" },
          ],
        },
        {
          id: "sis.herencia.datos",
          nombre: "Catálogos, consultas y dominios de backend",
          resumen: "Cómo está organizado hoy el consumo de datos del portal, y qué de eso conviene conservar o corregir.",
          pregunta: "¿Qué patrones del portal actual conviene conservar y cuáles corregir?",
          checks: [
            { id: "sis.herencia.datos.clasificadores", fuente: "codigo",
              label: "Conservar el catálogo de clasificadores de tipos de cargo que arma la portada de Pagos",
              verifica: "Es un buen patrón: agregar un tipo de cobro es cambio de catálogo, no de código. Confirmar que sigue así en SIR Plus" },
            { id: "sis.herencia.datos.plantillas", fuente: "codigo",
              label: "Conservar la configuración por plantilla: cerca de 20 tipos de paso y unos 30 tipos de padrón, con formularios descritos por configuración",
              verifica: "Inventario de tipos de paso y de padrón realmente usados por Jalisco, para no arrastrar los que no aplican" },
            { id: "sis.herencia.datos.calculo", fuente: "codigo",
              label: "Formas de cálculo del cargo: captura manual, monto fijo, tarifa, fórmula, múltiplo, porcentaje y función en servidor",
              verifica: "Casos de prueba por cada forma de cálculo, porque cada una falla distinto" },
            { id: "sis.herencia.datos.paginacion", fuente: "codigo",
              label: "Consultas que paginan recursivamente hasta agotar resultados por falta de un endpoint de listado completo",
              verifica: "Ocurre hoy con el listado de oficinas. Revisar dónde más pasa: crece en tiempo y en memoria conforme crece el padrón" },
            { id: "sis.herencia.datos.dominios", fuente: "codigo",
              label: "Dominios de backend separados: recaudación, trámites, solicitudes y reporteador",
              verifica: "Los PDF no se generan en el frontend: los pide un servicio de reporteador aparte del API principal. Mapa de qué canal consume qué dominio, y qué pasa si uno se cae" },
            { id: "sis.herencia.datos.bitacoras", fuente: "codigo",
              label: "Bitácoras paralelas por módulo (trámite y cita registran historial aparte del registro principal)",
              verifica: "Definir si esas bitácoras se unifican con el módulo de auditoría de SIR Plus o conviven, y cuál manda en una investigación" },
          ],
        },
      ],
    },
    {
      id: "sis-transversal",
      nombre: "Transversal al sistema",
      nodos: [
        {
          id: "sis.transversal.consistencia",
          nombre: "Consistencia entre los tres canales",
          resumen: "Admin, Portal y RETYS deben contar la misma historia sobre el mismo contribuyente.",
          pregunta: "¿Los tres canales usan la misma regla y el mismo dato?",
          checks: [
            { id: "sis.transversal.consistencia.reglas", fuente: "reco",
              label: "Una sola implementación del cálculo fiscal, consumida por los tres canales",
              verifica: "Revisión de código: que no existan tres cálculos de recargos distintos. Prueba cruzada del mismo cargo en los tres canales" },
            { id: "sis.transversal.consistencia.catalogos", fuente: "zoho",
              label: "Catálogos únicos, sin duplicidad entre canales",
              verifica: "Requisito de la tarea de contribuyente considerado: la relación debe funcionar en todos los canales y catálogos" },
            { id: "sis.transversal.consistencia.sesion", fuente: "reco",
              label: "Identidad del contribuyente compartida entre portal y trámites",
              verifica: "Prueba de continuidad: iniciar en el portal y continuar en RETYS sin volver a identificarse" },
          ],
        },
        {
          id: "sis.transversal.pendientes",
          nombre: "Correcciones que deben nacer resueltas",
          resumen: "Tareas marcadas en Zoho como 'aplica a todos los proyectos': si ya se corrigieron en otra entidad, SIR Plus no debe repetir el error.",
          pregunta: "¿Estas correcciones ya están en la nueva versión?",
          checks: [
            { id: "sis.transversal.pendientes.considerado", fuente: "zoho",
              label: "Padrón único de contribuyentes con contribuyente considerado (jubilado, pensionado)",
              verifica: "Tarea OAX en pausa, etiquetada 'aplica todos los proyectos'. Debe tener la misma funcionalidad que Ciudadano Considerado" },
            { id: "sis.transversal.pendientes.registro_pagos", fuente: "zoho",
              label: "Ventana de registro de pagos mostrando los cargos persistidos en la orden, no los cargos reales",
              verifica: "Tarea OAX 'Listo para producción': el desglose debe basarse en el JSON de cargos referenciados para que los totales cuadren" },
            { id: "sis.transversal.pendientes.validaciones", fuente: "zoho",
              label: "Validaciones integrales en backend para órdenes de pago y estados de cuenta",
              verifica: "Tarea OAX en pausa de operaciones: impedir el procesamiento de órdenes con datos inconsistentes antes de persistir" },
            { id: "sis.transversal.pendientes.reimpresion", fuente: "zoho",
              label: "Consistencia de datos en la reimpresión de la orden de pago (recargos y estatus saldado)",
              verifica: "Tarea OAX 'Listo para QA'" },
            { id: "sis.transversal.pendientes.bloqueo_cargos", fuente: "zoho",
              label: "Bloqueo en el módulo de cargos de los que provienen de trámites, infracciones y declaraciones empresariales",
              verifica: "Tarea OAX 'Listo para producción'" },
            { id: "sis.transversal.pendientes.auditoria_ep", fuente: "zoho",
              label: "Análisis de endpoints consumidos en procesos prioritarios, para poder auditar",
              verifica: "Tarea OAX 'Listo para QA': mapear cada servicio con su acción auditable, incluidos los de trámites" },
            { id: "sis.transversal.pendientes.bitacora", fuente: "zoho",
              label: "Revisión del endpoint de descuentos que consume espacio excesivo en bitácora",
              verifica: "Tarea NAV en pausa de desarrollo, etiquetada 'aplica todos los proyectos'" },
          ],
        },
        {
          id: "sis.transversal.calidad",
          nombre: "Calidad y aceptación",
          resumen: "Cómo demostramos que un módulo está terminado.",
          pregunta: "¿Quién firma que un módulo quedó bien?",
          checks: [
            { id: "sis.transversal.calidad.criterios", fuente: "reco",
              label: "Criterios de aceptación por módulo, acordados con el cliente antes de construir",
              verifica: "Documento firmado por módulo, con casos de prueba de negocio" },
            { id: "sis.transversal.calidad.uat", fuente: "reco",
              label: "Pruebas de aceptación con usuarios reales de recaudación de Jalisco",
              verifica: "Bitácora de la sesión de aceptación con hallazgos y su cierre" },
            { id: "sis.transversal.calidad.capacitacion", fuente: "reco",
              label: "Capacitación y manual de usuario por perfil (cajero, jefatura, administrador)",
              verifica: "Lista de asistencia y material entregado, con versión correspondiente al sistema liberado" },
            { id: "sis.transversal.calidad.soporte", fuente: "reco",
              label: "Mesa de ayuda definida para el arranque, con horario y escalamiento",
              verifica: "Procedimiento de soporte acordado y medición de tiempos de respuesta en la primera semana" },
          ],
        },
      ],
    },
  ],
};

export const CAPAS: Capa[] = [SISTEMA, DEVSECOPS, DEVOPS, INFRAESTRUCTURA];

/** Todos los ids de check de una capa — para calcular su semáforo. */
export function idsDeCapa(capa: Capa): string[] {
  return capa.grupos.flatMap(g => g.nodos.flatMap(n => n.checks.map(c => c.id)));
}

export function idsDeNodo(nodo: Nodo): string[] {
  return nodo.checks.map(c => c.id);
}

export const FUENTE_META: Record<Fuente, { label: string; color: string; titulo: string }> = {
  zoho:   { label: "Zoho",        color: "#C9A84C", titulo: "Tarea registrada en Zoho o hecho del tablero de operación" },
  codigo: { label: "Funcional",   color: "#2DD4BF", titulo: "Documentado en la Guía Funcional OPENSIR, elaborada desde el código fuente" },
  reco:   { label: "Recomendado", color: "#818CF8", titulo: "Recomendación de práctica — validar con el equipo antes de darla por cierta" },
};
